### ISSUE TITLE
add @elseif directive

### ISSUE THREAD

**Issue by hafizhaziq307** [aididalam/Codeigniter-Blade-Template#1]

**Comment by aididalam** [comment]
can please specify the issue?

**Comment by hafizhaziq307** [comment]
Currently for if statement, it only have @if, @else and @endif directives. It does not have @elseif directive. 

This is the example usecase for [@elseif](https://laravel.com/docs/9.x/blade#if-statements)

**Comment by aididalam** [comment]
### Added @elseif
